on:
  workflow_dispatch:
    inputs:
      prs:
        required: true
        description: ""
      to:
        required: true
        description: ""

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test workflow
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: foo
        uses: nakatamixi/pr-pick-action@main
        with:
          to: ${{github.event.inputs.to}}
          prs: ${{github.event.inputs.prs}}
          token: ${{ secrets.GITHUB_TOKEN }}
